# Numpy
- Numerical Python의 약자
- 산술 계산을 위한 패키지
 - 다차원 배열인 ndarray는 빠른 배열 계산을 제공
 - 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수
 - 선형대수, 난수 생성기, 푸리에 변환 가능
- 사용 목적 : 일반적인 산술 데이터 처리를 위한 기본 라이브러리를 제공해줌
 - 연산 처리 후 통계나 분석데이터를 처리하기위해 Pandas를 사용
- 파이썬 산술 계산 영역에서 중요한 위치를 차지하는 이유 중 하나는 대용량 데이터 배열을 효율적으로 다룰 수 있도록 설계되어 있기 때문
 


## Numpy 사용 예제

In [3]:
import numpy as np

my_arr = np.arange(100) 
my_list = list(range(100)) # 넘파이로 더 쉽게 만들기 가능

In [4]:
print(type(my_arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [5]:
print(my_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [6]:
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


### Numpy와 list의 연산 속도 비교 예제
- %time(매직함수) : 코드계산에 걸리는 시간이 표시

In [24]:
import numpy as np

my_arr = np.arange(10000) 
my_list = list(range(10000))

In [25]:
%time
for i in range(100):
    my_arr2 =  my_arr*2

Wall time: 0 ns


In [52]:
# 부록 - 궁금증
data = [1,2,3]
print(data*2)

[1, 2, 3, 1, 2, 3]


In [26]:
%time
for i in range(100):
    my_list2 = [i*2 for j in my_list]

Wall time: 0 ns


## 다차원 배열 객체
- Numpy는 ndarray라고 하는 N차원 배열 객체를 사용
 - 1차원 : Vectors
 - 2차원 : Matrices
 - 3차원 : Tensors

### 2 X 3 배열을 랜덤 생성

In [34]:
data = np.random.randn(2, 3)
print(data)

[[ 0.42500471  0.513575    0.10468586]
 [-0.60515958  0.16905296  0.66224484]]


### ndarray 생성하기 예제(list -> array)

In [35]:
data1 = [5, 7, 8, 1, 4]

In [36]:
type(data1)

list

In [37]:
arr1 = np.array(data1)

In [38]:
type(arr1)

numpy.ndarray

In [39]:
print(arr1)

[5 7 8 1 4]


### 2차원 배열 생성 예제

In [49]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # 괄호 두개 사용

In [50]:
print(arr1)

[[1 2 3]
 [4 5 6]]


## numpy 배열의 산술 연산
- numpy 배열은 반복문을 작성하지 않고 데이터를 일괄 처리할 수 있음
 - "벡터화" 라고 부름

In [53]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # 괄호 두개 사용

In [54]:
# 요소곱
print(arr1 * arr1)

[[ 1  4  9]
 [16 25 36]]


In [55]:
# 요소합
print(arr1 + arr1)

[[ 2  4  6]
 [ 8 10 12]]


In [56]:
# 요소 나눗셈
print(1 / arr1)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [59]:
# 논리연산 가능
print(arr1 == arr1)
print(arr1 > arr1)

[[ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]]


### 행렬곱 : 두개의 배열을 행과 렬을 곱하여 새로운 배열을 생성해냄(np.dot())

In [65]:
# 행렬곱
print(arr1)

[[1 2 3]
 [4 5 6]]


In [66]:
arr2 = np.transpose(arr1)
print(arr2)

[[1 4]
 [2 5]
 [3 6]]


In [67]:
print(np.dot(arr1, arr2))

[[14 32]
 [32 77]]


#### 3 X 3 행렬(범위 지정 후 모양을 다듬어서 생성) reshpe() 함수 사용

In [70]:
# 1차원 배열 생성
arr1 = np.array(range(1, 10))

In [69]:
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [76]:
# 부록
arr3 = np.arange(1, 10)
print(arr3)

[1 2 3 4 5 6 7 8 9]


In [89]:
# 2차원 3 X 3 배열 생성
arr2 = np.array(range(1, 10)).reshape(3, 3)

In [90]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 배열 인덱싱과 슬라이싱
- numpy 배열은 순차적(sequential) 데이터이기 때문에 인덱싱과 슬라이싱 가능

#### 배열 인덱싱 예제

In [77]:
arr1 = np.arange(10)

In [78]:
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [80]:
print(arr1[5])

5


In [81]:
print(arr1[5:8])

[5 6 7]


#### 다차원 배열 객체 연산
- 배열에서 연산을 수행할 때 
- 브로드캐스팅되어 연산됨

In [91]:
# 1 X 3 배열 + 정수
print(np.arange(3) + 5)

[5 6 7]


In [101]:
# 3 X 3 배열 + 1 X 3 배열
print(np.ones((3, 3)) + np.arange(3)) 
     # 1로 다 채워줌

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [102]:
# 3 X 1 배열 + 1 X 3 배열
print(np.arange(3).reshape(3, 1) + np.arange(3))

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 배열 전치와 축 바꾸기
- np.transpose() or T 사용

In [103]:
arr = np.arange(15).reshape(3, 5)

In [104]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [105]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


np.transpose(np.array([[0, 1, 2]])
- 2차원 배열이기 때문에 전치와 축 바꾸기 가능

np.transpose(np.arange(3)), type(np.arrange(3)))
- 1차원 배열은 전치와 축 바꾸기 불가능

3차원 배열 만들기

In [109]:
arr = np.array([[[1,2,3,4],
                [5, 6, 7,8],
                 [9,10,11,12]],
                [[11,12,13,14],
                [15,16,17,18],
                [19,20,21,22]]
                
                
                
                ])

In [110]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


### numpy 배열을 pandas dataframe으로 바꾸는 방법

In [111]:
arr = np.arange(15).reshape(3, 5)

In [114]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [112]:
import pandas as pd
df = pd.DataFrame(arr)

In [113]:
print(df)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14


## <부록>Numpy를 어디서 쓰는가<br>
1. 이미지 데이터 처리 : 행렬->사진(픽셀)